# Generated by Django 5.1.1 on 2024-11-21 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="userName",
            new_name="username",
        ),
    ]
