# Generated by Django 5.1.1 on 2024-11-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_workout"),
    ]

    operations = [
        migrations.CreateModel(
            name="PresetExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("tutorial_url", models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name="Workout",
        ),
    ]
